new nav minus Academy page
DevDogs-UGA/DevDogs-Website pull request #108
Opened 2024-10-20 18:47 UTC by jayp822

Sorry haven't been active for a while but here is a new navbar. The video shows the academy page but I commented it out in the commit. Also the CI CD is going to fail because of old pushes to the main branch where the person didn't do the react-props. 

![Screenshot 2024-10-20 at 2 43 34 PM](https://github.com/user-attachments/assets/c5df0eb0-f615-4231-9b38-ecf1af91fdf8)

https://github.com/user-attachments/assets/a733acd3-9ef2-4c53-b65d-f770146acbc8

2024-10-24 10:17 UTC, jayp822 commented
![image](https://github.com/user-attachments/assets/bb40cc59-b12e-41a6-a150-f3f11b38350e)
added this for now so CI CD passes but should be removed to fix warnings in the future

2024-10-29 04:41 UTC, justinquinnb commented
For the sake of improved UX on mobile, I advise right-justifying the dropdown menu items on mobile so they can be easily accessible to someone's right thumb

2024-10-29 15:49 UTC, jayp822 commented
> vise right-justifying the dropdown menu items on mobile so they can be easily accessible to someone's righ

good point

2024-10-31 22:08 UTC, nivedhanatarajan7 commented
> > vise right-justifying the dropdown menu items on mobile so they can be easily accessible to someone's righ
> > ![Screenshot 2024-10-29 115610](https://private-user-images.githubusercontent.com/81924044/381207883-a62f5ee2-108e-421e-bf12-84db4e3efee1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MTI2MzIsIm5iZiI6MTczMDQxMjMzMiwicGF0aCI6Ii84MTkyNDA0NC8zODEyMDc4ODMtYTYyZjVlZTItMTA4ZS00MjFlLWJmMTItODRkYjRlM2VmZWUxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDIyMDUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MWQ4YWNkZmYyMjI4YzdhNmY1ZWQwMGM1MjRhOGFhZDQ3ZWZmNmI2NDg2YTQ5YmIzOWY2MmEzMWQyZGZjNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2fOQMcHuaPcWV-zJ_Iqnygl5EkY6us_jN_8X8SmT-5c)
> 
> like this?

Yes, that looks good. Would it be possible to make it look like there is a drop down for the main sections like Home, Partners, and About? That way the navbar will look more clears and less crowded on the phone screen.

2024-10-31 22:10 UTC, nivedhanatarajan7 commented
Would it be possible to also give the circle icon a default person icon image or something default? That way it is more obvious that clicking on the circle will lead to log in authentication and account details.

2024-11-01 01:30 UTC, jayp822 commented
https://github.com/user-attachments/assets/afe29d29-d333-4b37-a71b-815b17b42bac

what do you think about it being like this instead

2024-11-01 19:28 UTC, nivedhanatarajan7 requested changes

2024-11-01 19:28 UTC, nivedhanatarajan7 commented on src/app/components/NavBar.js
Currently, the navbar looks like this:
![image](https://github.com/user-attachments/assets/d01d350c-37e7-4ee9-8d2d-66bb4e92b6d7)
Please make the Home and Contact links also right justified. 

In addition, when the Partners dropdown is expanded, and the user clicks the About dropdown, the Partners dropdown is automatically collapsed. However, when the About dropdown is expanded and the user clicks the dropdown for Partners, it only collapses the dropdown for About and does not automatically expand Partners until after another click. Can you make this transition smoother?

Thank you so much! The Navbar looks great overall, these would be some additional adjustments to make it better!

2024-11-01 19:30 UTC, nivedhanatarajan7 commented
> Screen.Recording.2024-10-31.at.9.30.09.PM.mov 
> what do you think about it being like this instead

Can you expand more on the use of this style of navbar? For example, would this be for mobile, desktop, or both, and why you prefer this style over the current style of the navbar (always visible at top of page in desktop, and clicking the button to see the navbar and expandable categories in mobile).

2024-11-01 20:22 UTC, jayp822 commented
im not having the problems you described In the photo mine commit "updates" works fine for me.

2025-10-17 00:36 UTC, closed without merging