Everything sponsor
DevDogs-UGA/DevDogs-Website pull request #63
Opened 2024-08-21 21:39 UTC by jayp822

added sponsor us an our sponsor to nav bar and implemented the nav bar tab bold red when you are on that directory. Other fixes from un merged pull requests.

https://github.com/user-attachments/assets/8cc41403-4a35-4553-ac0c-f066086ae5c9

2024-08-21 21:48 UTC, justinquinnb reviewed
The sponsor pages were still in the design stage, they weren't ready for development. I'm so sorry I forgot to hide them on the Figma. Save your progress on them since the pages will be similar, but let's not publish those changes quite yet. All other changes look good though!

2024-08-21 21:49 UTC, jayp822 commented
Ok ill just comment it out for now

2024-08-21 21:53 UTC, justinquinnb commented
Another comment I've just noticed--the text on the Our People page is incorrect. Looks like a simple copy-paste error from the Figma, as that's the text that's supposed to just be on the Our Projects page.

Intended text:
> DevDogs is proud to consist of over 180 UGA students from all tech disciplines and backgrounds. We firmly believe that different perspectives breed the best solutions--and we think our work shows! Take a look at some of the awesome people that have made DevDogs, DevDogs below.

2024-08-21 22:53 UTC, nivedhanatarajan7 commented
It seems like the display with different device widths are different. In the video you provided, it looks fine. However on some devices it looks like this 
![image](https://github.com/user-attachments/assets/51cdc636-7978-4edb-a8e1-988102d0e473)
![image](https://github.com/user-attachments/assets/713a71df-4707-423b-a42e-902b4f3e3512)

2024-08-21 23:01 UTC, jayp822 commented
> In the video you provided, it looks fine. However on some devices it looks like this

fixed

2024-08-22 02:42 UTC, ggliv commented on src/app/about/page.js
> +                    </div> */}
```suggestion
```
Please don't do this. We have source control to track previous versions.

2024-08-22 02:53 UTC, ggliv requested changes
Quick, incomplete glance over from a style perspective.

2024-08-22 02:53 UTC, ggliv commented on src/app/about/people/page.js
> +// import FlippableCard from "@/app/components/FlippableCard";
```suggestion
```

2024-08-22 02:53 UTC, ggliv commented on src/app/about/page.js
> +                    </div> */}
```suggestion
```
Please don't do this. We have source control to keep track of previous versions.

2024-08-22 02:53 UTC, ggliv commented on src/app/components/FlippableCard.js
> +/* eslint-disable react/prop-types */
`PropTypes` are probably enabled by default for a reason. Please avoid lint overrides like this. If you think `PropTypes` should be disabled project-wide, open an issue and make your case there.

2024-08-22 02:53 UTC, ggliv commented on src/app/components/FlippableCard.js
> +// import { GitHubIcon } from "@/app/images/github.svg";
```suggestion
import Image from "next/image";
```

2024-08-24 14:54 UTC, merged

2024-08-24 14:55 UTC, nivedhanatarajan7 reviewed
The changes look good. Thank you!