Campus partners page
DevDogs-UGA/DevDogs-Website pull request #90
Opened 2024-09-12 21:31 UTC by jayp822

Don't know what to put in the carousel slides but I can add it. 
![demo11](https://github.com/user-attachments/assets/7dfcfd0f-cd3e-4ddb-be44-28ec3c8ee18d)

2024-09-12 23:00 UTC, justinquinnb commented
Will send shortly, thank you!

2024-09-12 23:01 UTC, justinquinnb commented
Just noticed, affiliates is missing an extra F!

2024-09-13 00:57 UTC, justinquinnb commented
ACM: https://acm-uga.github.io/
CSCI: https://uga.campuslabs.com/engage/organization/csci
SOE: https://www.soeuga.com/
KTP: https://ktpgeorgia.com/

I will have to make card images for these clubs tonight, which I'll add here, since we don't have an asset library from them.

2024-09-15 23:26 UTC, justinquinnb commented
Here are the values for the card fields. Check out the Figma, we've since added Hacks and now have an official GDGC wordmark you need to change out.

![HacksX Card Image](https://github.com/user-attachments/assets/8bbc9392-df76-4bd4-ab47-a71930ffb4bd)
**Club Name:** UGA Hacks
**Club Description:** Every spring, UGA Hacks puts on a 3-day, 800+ person hackathon at MLC.

![SOE Card Image](https://github.com/user-attachments/assets/5d55f86e-3f23-4586-95ee-579ab64645f7)
**Club Name:** Society of Entrepreneurs
**Club Description:** Learn from and connect with founders and business-savvy individuals at SOE's many events.

![ACM Card Image](https://github.com/user-attachments/assets/bccc57fd-6473-4e44-8759-38c5a8562c8c)
**Club Name:** ACM @ UGA
**Club Description:** Every week, ACM hosts workshops discussing the latest technologies.

![CSCI Card Image](https://github.com/user-attachments/assets/fec53170-ee19-4556-ac5b-ab413deacdb9)
**Club Name:** Computer Science Career Initiative
**Club Description:** CSCI provides resources to assist students in their pursuit of a many technical fields.

![KTP Card Image](https://github.com/user-attachments/assets/f5f3848d-d4f8-458e-b3c3-0928d8e32c6a)
**Club Name:** Kappa Theta Pi: Phi Colony
**Club Description:** KTP is UGA's first technology frat, developing the next generation of industry professionals.

![GDGC Card Image](https://github.com/user-attachments/assets/e9e914d1-1a53-4a83-af58-6db0f3931737)
**Club Name:** Google Developer Groups on Campus: UGA
**Club Description:** GDGC UGA co-hosts their meetings with DevDogs, getting you in the Google sphere.

2024-09-17 00:33 UTC, jayp822 commented
https://github.com/user-attachments/assets/33e9b821-52b3-4bdb-8961-47dd1a33d0e1

2024-09-18 00:24 UTC, justinquinnb commented
Give me a ping when you finish the final touches. Since my last comment, we also finally got a GDGC page going that you can add to the card if possible: https://gdg.community.dev/gdg-on-campus-university-of-georgia-athens-united-states/
![image](https://github.com/user-attachments/assets/df3167ac-e4bf-4ae2-99ac-ebcb8a24e65f)

2024-09-25 16:46 UTC, nivedhanatarajan7 requested changes
Hi! The campus partners page looks really great! I gave some comments on spacing in the page. Thank you!

2024-09-25 16:46 UTC, nivedhanatarajan7 commented on src/app/sponsor/our-partners/page.js
> +        reverse="true"
I think the space between the title and the next line can be shorter.

Web View:
![image](https://github.com/user-attachments/assets/4e223bae-08a9-4073-ac5d-8e3a59ccbd6b)

Mobile View:
![image](https://github.com/user-attachments/assets/49c3838c-3a38-4faf-a071-950f2bf9f68a)

2024-09-25 16:46 UTC, nivedhanatarajan7 commented on src/app/sponsor/our-partners/page.js
> +
The space between the carousel and the campus partners' images can be shorter in mobile view.

Mobile view:
![image](https://github.com/user-attachments/assets/d66d3577-a11c-4d4a-a970-fae47eee989e)

2024-10-12 19:04 UTC, nivedhanatarajan7 approved these changes

2024-10-12 19:04 UTC, merged